# Generated by Django 5.2.17 on 2026-08-30 18:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready for Submission'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('action_required', 'Action Required'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('declaration_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_info_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('needs_correction', 'Needs Correction')], default='not_started', max_length=20)),
                ('hostel_required', models.BooleanField(blank=True, null=True)),
                ('scholarship_required', models.BooleanField(blank=True, null=True)),
                ('disability_status', models.BooleanField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_info', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_info_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('needs_correction', 'Needs Correction')], default='not_started', max_length=20)),
                ('matric_board', models.CharField(blank=True, max_length=150, verbose_name='Matric Group')),
                ('matric_year', models.PositiveIntegerField(blank=True, null=True)),
                ('matric_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('matric_total_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('matric_grade', models.CharField(blank=True, max_length=20)),
                ('intermediate_result', models.CharField(blank=True, max_length=20)),
                ('intermediate_board', models.CharField(blank=True, max_length=150, verbose_name='Intermediate / A-Level Board')),
                ('intermediate_group', models.CharField(blank=True, max_length=50)),
                ('intermediate_year', models.PositiveIntegerField(blank=True, null=True)),
                ('intermediate_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('intermediate_total_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('intermediate_grade', models.CharField(blank=True, max_length=20)),
                ('degree_program', models.CharField(blank=True, max_length=100)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_info', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='ContactAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_address_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('needs_correction', 'Needs Correction')], default='not_started', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator('^92\\d{10}$', 'Enter a valid phone number starting with 92 followed by 10 digits.')])),
                ('alternate_phone', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator('^92\\d{10}$', 'Enter a valid phone number starting with 92 followed by 10 digits.')])),
                ('permanent_address', models.TextField(blank=True, max_length=200)),
                ('present_address', models.TextField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator("^[A-Za-z]+(?:[ '-][A-Za-z]+)*$", 'Use letters, spaces, hyphens, or apostrophes only.')])),
                ('province', models.CharField(blank=True, choices=[('Punjab', 'Punjab'), ('Sindh', 'Sindh'), ('Khyber Pakhtunkhwa', 'Khyber Pakhtunkhwa'), ('Balochistan', 'Balochistan'), ('Gilgit-Baltistan', 'Gilgit-Baltistan'), ('Azad Jammu & Kashmir', 'Azad Jammu & Kashmir'), ('Islamabad Capital Territory', 'Islamabad Capital Territory')], max_length=30)),
                ('postal_code', models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]{4,6}$', 'Enter a valid postal code.')])),
                ('district', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator("^[A-Za-z]+(?:[ '-][A-Za-z]+)*$", 'Use letters, spaces, hyphens, or apostrophes only.')])),
                ('domicile_province', models.CharField(blank=True, choices=[('Punjab', 'Punjab'), ('Sindh', 'Sindh'), ('Khyber Pakhtunkhwa', 'Khyber Pakhtunkhwa'), ('Balochistan', 'Balochistan'), ('Gilgit-Baltistan', 'Gilgit-Baltistan'), ('Azad Jammu & Kashmir', 'Azad Jammu & Kashmir'), ('Islamabad Capital Territory', 'Islamabad Capital Territory')], max_length=30)),
                ('domicile_district', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator("^[A-Za-z]+(?:[ '-][A-Za-z]+)*$", 'Use letters, spaces, hyphens, or apostrophes only.')])),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_address', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documents_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('needs_correction', 'Needs Correction')], default='not_started', max_length=20)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents_summary', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='GuardianInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian_info_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('needs_correction', 'Needs Correction')], default='not_started', max_length=20)),
                ('guardian_name', models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator("^[A-Za-z]+(?:[ '-][A-Za-z]+)*$", 'Use letters, spaces, hyphens, or apostrophes only.')])),
                ('guardian_relationship', models.CharField(blank=True, max_length=50)),
                ('guardian_cnic', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{7}-\\d$', 'Format: 12345-1234567-1.')])),
                ('guardian_occupation', models.CharField(blank=True, max_length=150)),
                ('guardian_phone', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator('^92\\d{10}$', 'Enter a valid phone number starting with 92 followed by 10 digits.')])),
                ('guardian_email', models.EmailField(blank=True, max_length=254)),
                ('guardian_address', models.TextField(blank=True)),
                ('guardian_income', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator("^[A-Za-z]+(?:[ '-][A-Za-z]+)*$", 'Use letters, spaces, hyphens, or apostrophes only.')])),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator('^92\\d{10}$', 'Enter a valid phone number starting with 92 followed by 10 digits.')])),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_info', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_info_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('needs_correction', 'Needs Correction')], default='not_started', max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator("^[A-Za-z]+(?:[-'][A-Za-z]+)*$", 'Use letters only.')])),
                ('last_name', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator("^[A-Za-z]+(?:[-'][A-Za-z]+)*$", 'Use letters only.')])),
                ('father_name', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator("^[A-Za-z]+(?:[ '-][A-Za-z]+)*$", 'Use letters, spaces, hyphens, or apostrophes only.')])),
                ('mother_name', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator("^[A-Za-z]+(?:[ '-][A-Za-z]+)*$", 'Use letters, spaces, hyphens, or apostrophes only.')])),
                ('cnic_or_bform', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{7}-\\d$', 'Format: 12345-1234567-1.')], verbose_name='CNIC / B-Form Number')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('nationality', models.CharField(blank=True, default='Pakistani', max_length=50)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('marital_status', models.CharField(blank=True, max_length=12)),
                ('student_photo', models.TextField(blank=True, null=True)),
                ('student_photo_type', models.CharField(blank=True, max_length=20)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to='applications.application')),
            ],
        ),
    ]
