# Generated by Django 5.2.17 on 2026-08-12 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready for Submission'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('action_required', 'Action Required'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('personal_info_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('needs_correction', 'Needs Correction')], default='not_started', max_length=20)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('father_name', models.CharField(blank=True, max_length=150)),
                ('cnic_or_bform', models.CharField(blank=True, max_length=20, verbose_name='CNIC / B-Form Number')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('nationality', models.CharField(blank=True, default='Pakistani', max_length=50)),
                ('contact_address_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('needs_correction', 'Needs Correction')], default='not_started', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('permanent_address', models.TextField(blank=True)),
                ('present_address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=15)),
                ('academic_info_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('needs_correction', 'Needs Correction')], default='not_started', max_length=20)),
                ('matric_board', models.CharField(blank=True, max_length=150, verbose_name='Matric / O-Level Board')),
                ('matric_year', models.PositiveIntegerField(blank=True, null=True)),
                ('matric_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('matric_total_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('intermediate_board', models.CharField(blank=True, max_length=150, verbose_name='Intermediate / A-Level Board')),
                ('intermediate_year', models.PositiveIntegerField(blank=True, null=True)),
                ('intermediate_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('intermediate_total_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('entry_test_score', models.CharField(blank=True, max_length=50)),
                ('guardian_info_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('needs_correction', 'Needs Correction')], default='not_started', max_length=20)),
                ('guardian_name', models.CharField(blank=True, max_length=150)),
                ('guardian_relationship', models.CharField(blank=True, max_length=50)),
                ('guardian_cnic', models.CharField(blank=True, max_length=20)),
                ('guardian_occupation', models.CharField(blank=True, max_length=150)),
                ('guardian_phone', models.CharField(blank=True, max_length=20)),
                ('guardian_email', models.EmailField(blank=True, max_length=254)),
                ('guardian_address', models.TextField(blank=True)),
                ('documents_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('needs_correction', 'Needs Correction')], default='not_started', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
