# Generated by Django 5.2.17 on 2026-08-31 10:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready for Submission'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('action_required', 'Action Required'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('declaration_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('needs_correction', 'Needs Correction')], default='not_started', max_length=20)),
                ('entry_test_option', models.CharField(choices=[('need_to_appear', 'Need to Appear in Test'), ('already_qualified', 'Already Qualified Entrance Test'), ('exempted', 'Exempted from Test')], max_length=20)),
                ('test_center', models.CharField(choices=[('peshawar', 'Peshawar'), ('lahore', 'Lahore'), ('karachi', 'Karachi'), ('islamabad', 'Islamabad'), ('quetta', 'Quetta'), ('multan', 'Multan'), ('other', 'Other')], max_length=20)),
                ('test_center_name', models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator("^[A-Za-z0-9][A-Za-z0-9&.,'\\-\\s]*$", 'Enter a valid name.')])),
                ('test_type', models.CharField(blank=True, choices=[('nts', 'NTS'), ('ecat', 'ECAT'), ('mcat', 'MCAT'), ('sat', 'SAT'), ('university_specific', 'University-Specific Test'), ('other', 'Other')], max_length=30)),
                ('obtained_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_of_test', models.DateField(blank=True, null=True)),
                ('evidence_document', models.TextField(blank=True, null=True)),
                ('evidence_document_type', models.CharField(blank=True, max_length=20)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission_test', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('needs_correction', 'Needs Correction')], default='not_started', max_length=20)),
                ('admission_scheme', models.CharField(choices=[('open_merit', 'Open Merit'), ('self_finance', 'Self Finance'), ('special_quota', 'Special Quota'), ('overseas_pakistani', 'Overseas Pakistani'), ('other', 'Other')], max_length=30, verbose_name='Admission Scheme')),
                ('ga_ship_interest', models.BooleanField(blank=True, null=True, verbose_name='GA-ship Interest')),
                ('day_scholar_interest', models.BooleanField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission_scheme', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('needs_correction', 'Needs Correction')], default='not_started', max_length=20)),
                ('hostel_required', models.BooleanField(blank=True, null=True)),
                ('scholarship_required', models.BooleanField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_info', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('needs_correction', 'Needs Correction')], default='not_started', max_length=20)),
                ('degree_certificate', models.CharField(choices=[('matric', 'Matric / SSC'), ('intermediate', 'Intermediate / A-Level'), ('bachelor', "Bachelor's"), ('master', "Master's"), ('other', 'Other')], max_length=20, verbose_name='Degree / Certificate')),
                ('board_university', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator("^[A-Za-z0-9][A-Za-z0-9&.,'\\-\\s]*$", 'Enter a valid name.')], verbose_name='Board / University')),
                ('degree_title', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator("^[A-Za-z0-9][A-Za-z0-9&.,'\\-\\s]*$", 'Enter a valid name.')])),
                ('institute_name', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator("^[A-Za-z0-9][A-Za-z0-9&.,'\\-\\s]*$", 'Enter a valid name.')])),
                ('obtained_marks', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Obtained Marks / CGPA')),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Marks / Scale (for CGPA)')),
                ('passing_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2035)])),
                ('study_group', models.CharField(choices=[('pre_medical', 'Pre-Medical'), ('pre_engineering', 'Pre-Engineering'), ('computer_science', 'Computer Science'), ('commerce', 'Commerce'), ('arts_humanities', 'Arts / Humanities'), ('general_science', 'General Science'), ('other', 'Other')], max_length=30)),
                ('country_studied', models.CharField(default='Pakistan', max_length=50, validators=[django.core.validators.RegexValidator("^[A-Za-z]+(?:[ '-][A-Za-z]+)*$", 'Use letters, spaces, hyphens, or apostrophes only.')])),
                ('result_declared', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_info', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='ContactAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('needs_correction', 'Needs Correction')], default='not_started', max_length=20)),
                ('mailing_same_as_permanent', models.BooleanField(default=False, help_text='If checked, mailing address is copied from the permanent address.')),
                ('permanent_house_street_no', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9][A-Za-z0-9\\s,\\-/#.]*$', 'Enter a valid address (letters, numbers, and , - / # . only).')], verbose_name='House No. & Street No.')),
                ('permanent_mohalla_tehsil', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator("^[A-Za-z]+(?:[ '-][A-Za-z]+)*$", 'Use letters, spaces, hyphens, or apostrophes only.')], verbose_name='Mohalla / Village / Tehsil')),
                ('permanent_district', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator("^[A-Za-z]+(?:[ '-][A-Za-z]+)*$", 'Use letters, spaces, hyphens, or apostrophes only.')])),
                ('permanent_city', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator("^[A-Za-z]+(?:[ '-][A-Za-z]+)*$", 'Use letters, spaces, hyphens, or apostrophes only.')])),
                ('permanent_phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^92\\d{10}$', 'Enter a valid phone number starting with 92 followed by 10 digits.')])),
                ('permanent_courier_available', models.BooleanField(blank=True, null=True)),
                ('mailing_house_street_no', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9][A-Za-z0-9\\s,\\-/#.]*$', 'Enter a valid address (letters, numbers, and , - / # . only).')], verbose_name='House No. & Street No.')),
                ('mailing_mohalla_tehsil', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator("^[A-Za-z]+(?:[ '-][A-Za-z]+)*$", 'Use letters, spaces, hyphens, or apostrophes only.')], verbose_name='Mohalla / Village / Tehsil')),
                ('mailing_district', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator("^[A-Za-z]+(?:[ '-][A-Za-z]+)*$", 'Use letters, spaces, hyphens, or apostrophes only.')])),
                ('mailing_city', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator("^[A-Za-z]+(?:[ '-][A-Za-z]+)*$", 'Use letters, spaces, hyphens, or apostrophes only.')])),
                ('mailing_phone', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator('^92\\d{10}$', 'Enter a valid phone number starting with 92 followed by 10 digits.')])),
                ('mailing_courier_available', models.BooleanField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_address', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('needs_correction', 'Needs Correction')], default='not_started', max_length=20)),
                ('no_employment_history', models.BooleanField(default=False)),
                ('employer', models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator("^[A-Za-z0-9][A-Za-z0-9&.,'\\-\\s]*$", 'Enter a valid name.')])),
                ('job_title', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator("^[A-Za-z]+(?:[ '-][A-Za-z]+)*$", 'Use letters, spaces, hyphens, or apostrophes only.')])),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('still_working_here', models.BooleanField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_employment', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documents_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('needs_correction', 'Needs Correction')], default='not_started', max_length=20)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents_summary', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('needs_correction', 'Needs Correction')], default='not_started', max_length=20)),
                ('student_photo', models.TextField(blank=True, null=True)),
                ('student_photo_type', models.CharField(blank=True, max_length=20)),
                ('full_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator("^[A-Za-z]+(?:[ '-][A-Za-z]+)*$", 'Use letters, spaces, hyphens, or apostrophes only.')])),
                ('father_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator("^[A-Za-z]+(?:[ '-][A-Za-z]+)*$", 'Use letters, spaces, hyphens, or apostrophes only.')])),
                ('guardian_name', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator("^[A-Za-z]+(?:[ '-][A-Za-z]+)*$", 'Use letters, spaces, hyphens, or apostrophes only.')])),
                ('guardian_contact_no', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^92\\d{10}$', 'Enter a valid phone number starting with 92 followed by 10 digits.')], verbose_name='Father / Guardian Contact No.')),
                ('cell_no', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^92\\d{10}$', 'Enter a valid phone number starting with 92 followed by 10 digits.')])),
                ('religion', models.CharField(choices=[('Islam', 'Islam'), ('Christianity', 'Christianity'), ('Hinduism', 'Hinduism'), ('Sikhism', 'Sikhism'), ('Other', 'Other')], max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('nationality', models.CharField(choices=[('Pakistani', 'Pakistani'), ('Other', 'Other')], default='Pakistani', max_length=50)),
                ('cnic', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{7}-\\d$', 'Format: 12345-1234567-1.')], verbose_name='CNIC / B-Form Number')),
                ('passport_no', models.CharField(blank=True, help_text='Only applicable if nationality is not Pakistani.', max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z]{1,2}[0-9]{6,7}$', 'Enter a valid passport number, e.g. AB1234567.')])),
                ('domicile_province', models.CharField(choices=[('Punjab', 'Punjab'), ('Sindh', 'Sindh'), ('Khyber Pakhtunkhwa', 'Khyber Pakhtunkhwa'), ('Balochistan', 'Balochistan'), ('Gilgit-Baltistan', 'Gilgit-Baltistan'), ('Azad Jammu & Kashmir', 'Azad Jammu & Kashmir'), ('Islamabad Capital Territory', 'Islamabad Capital Territory')], max_length=30)),
                ('domicile_district', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator("^[A-Za-z]+(?:[ '-][A-Za-z]+)*$", 'Use letters, spaces, hyphens, or apostrophes only.')])),
                ('disability_status', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, verbose_name='Do you have any disability?')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('needs_correction', 'Needs Correction')], default='not_started', max_length=20)),
                ('bank_provider_name', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator("^[A-Za-z0-9][A-Za-z0-9&.,'\\-\\s]*$", 'Enter a valid name.')])),
                ('payment_mode', models.CharField(choices=[('bank_deposit', 'Bank Deposit'), ('online_transfer', 'Online Transfer'), ('easypaisa_jazzcash', 'Easypaisa / JazzCash'), ('pay_order', 'Pay Order / Demand Draft'), ('other', 'Other')], max_length=30)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('reference_number', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9\\-/]+$', 'Use letters, numbers, hyphens, and slashes only.')])),
                ('proof_of_payment', models.TextField(blank=True, null=True)),
                ('proof_of_payment_type', models.CharField(blank=True, max_length=20)),
                ('fee_deposited', models.BooleanField(default=False)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processing_fee', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('needs_correction', 'Needs Correction')], default='not_started', max_length=20)),
                ('program_choice', models.CharField(choices=[('bs_computer_science', 'BS Computer Science'), ('bs_software_engineering', 'BS Software Engineering'), ('bs_electrical_engineering', 'BS Electrical Engineering'), ('bs_business_administration', 'BS Business Administration'), ('bs_accounting_finance', 'BS Accounting & Finance'), ('bs_english', 'BS English'), ('bs_psychology', 'BS Psychology'), ('md_medicine', 'MBBS'), ('other', 'Other')], max_length=50)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='program_preference', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='RefereeInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('needs_correction', 'Needs Correction')], default='not_started', max_length=20)),
                ('referee_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator("^[A-Za-z]+(?:[ '-][A-Za-z]+)*$", 'Use letters, spaces, hyphens, or apostrophes only.')])),
                ('contact_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^92\\d{10}$', 'Enter a valid phone number starting with 92 followed by 10 digits.')])),
                ('email', models.EmailField(max_length=254)),
                ('university_name', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator("^[A-Za-z0-9][A-Za-z0-9&.,'\\-\\s]*$", 'Enter a valid name.')])),
                ('designation', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator("^[A-Za-z]+(?:[ '-][A-Za-z]+)*$", 'Use letters, spaces, hyphens, or apostrophes only.')])),
                ('recommendation_letter', models.TextField(blank=True, null=True)),
                ('recommendation_letter_type', models.CharField(blank=True, max_length=20)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referee_information', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='TestCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('needs_correction', 'Needs Correction')], default='not_started', max_length=20)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_center', to='applications.application')),
            ],
        ),
    ]
