# Generated by Django 5.2.17 on 2026-08-31 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentssummary',
            name='application',
        ),
        migrations.DeleteModel(
            name='AdditionalInfo',
        ),
        migrations.DeleteModel(
            name='DocumentsSummary',
        ),
    ]
