# Generated by Django 5.2.17 on 2026-08-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_additional_info_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='student_photo_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='student_photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
