# Generated by Django 5.2.17 on 2026-08-15 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_student_photo_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]{11}$', 'Enter a valid 11 digit mobile number.')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='city',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+$', 'Letters only.')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='cnic_or_bform',
            field=models.CharField(blank=True, max_length=15, unique=True, null=True, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{7}-\\d$', 'Format: 12345-1234567-1.')], verbose_name='CNIC / B-Form Number'),
        ),
        migrations.AlterField(
            model_name='application',
            name='district',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+$', 'Letters only.')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='domicile_district',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+$', 'Letters only.')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='domicile_province',
            field=models.CharField(choices=[('Punjab', 'Punjab'), ('Sindh', 'Sindh'), ('Khyber Pakhtunkhwa', 'Khyber Pakhtunkhwa'), ('Balochistan', 'Balochistan'), ('Gilgit-Baltistan', 'Gilgit-Baltistan'), ('Azad Jammu & Kashmir', 'Azad Jammu & Kashmir'), ('Islamabad Capital Territory', 'Islamabad Capital Territory')], max_length=30),
        ),
        migrations.AlterField(
            model_name='application',
            name='email_address',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+$', 'Letters only.')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]{11}$', 'Enter a valid 11 digit mobile number.')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='father_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+$', 'Letters only.')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-Za-z]+$', 'Letters only.')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+$', 'Letters only.')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='guardian_cnic',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{7}-\\d$', 'Format: 12345-1234567-1.')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+$', 'Letters only.')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]{11}$', 'Enter a valid 11 digit mobile number.')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-Za-z]+$', 'Letters only.')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='mother_name',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+$', 'Letters only.')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='permanent_address',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]{11}$', 'Enter a valid 11 digit mobile number.')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='postal_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]{4,6}$', 'Enter a valid postal code.')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='present_address',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='application',
            name='province',
            field=models.CharField(choices=[('Punjab', 'Punjab'), ('Sindh', 'Sindh'), ('Khyber Pakhtunkhwa', 'Khyber Pakhtunkhwa'), ('Balochistan', 'Balochistan'), ('Gilgit-Baltistan', 'Gilgit-Baltistan'), ('Azad Jammu & Kashmir', 'Azad Jammu & Kashmir'), ('Islamabad Capital Territory', 'Islamabad Capital Territory')], max_length=30),
        ),
        migrations.AlterField(
            model_name='application',
            name='student_photo_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]{11}$', 'Enter a valid 11 digit mobile number.')]),
        ),
    ]
