# Generated by Django 5.2.17 on 2026-08-31 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_additionalinfo_documentssummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentssummary',
            name='application',
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('needs_correction', 'Needs Correction')], default='not_started', max_length=20)),
                ('declaration_accepted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application_form', to='applications.application')),
            ],
        ),
        migrations.DeleteModel(
            name='AdditionalInfo',
        ),
        migrations.DeleteModel(
            name='DocumentsSummary',
        ),
    ]
