# Generated by Django 5.2.17 on 2026-09-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_remove_documentssummary_application_formsubmission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programpreference',
            name='program_choice',
        ),
        migrations.AddField(
            model_name='programpreference',
            name='degree_level',
            field=models.CharField(choices=[('ms', 'MS'), ('phd', 'PhD')], default='ms', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programpreference',
            name='discipline',
            field=models.CharField(choices=[('computer_engineering', 'Computer Engineering'), ('computer_science', 'Computer Science'), ('chemical_engineering', 'Chemical Engineering'), ('civil_engineering', 'Civil Engineering'), ('electronics_engineering', 'Electronics Engineering'), ('electrical_engineering', 'Electrical Engineering'), ('engineering_sciences_applied_mathematics', 'Engineering Sciences (Applied Mathematics)'), ('engineering_sciences_applied_physics', 'Engineering Sciences (Applied Physics)'), ('engineering_sciences_engineering', 'Engineering Sciences (Engineering)'), ('mechanical_engineering', 'Mechanical Engineering'), ('materials_engineering', 'Materials Engineering'), ('nanotechnology_materials_engineering', 'Nanotechnology and Materials Engineering'), ('engineering_management', 'Engineering Management'), ('other', 'Other')], default='chemical_engineering', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcenter',
            name='preferred_test_center',
            field=models.CharField(choices=[('peshawar', 'Peshawar'), ('lahore', 'Lahore'), ('karachi', 'Karachi'), ('islamabad', 'Islamabad'), ('quetta', 'Quetta'), ('multan', 'Multan'), ('other', 'Other')], default='lahore', max_length=20, verbose_name='Preferred Test Center'),
            preserve_default=False,
        ),
    ]
