# Generated by Django 5.2.17 on 2026-08-15 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_application_cnic_or_bform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cnic_or_bform',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{7}-\\d$', 'Format: 12345-1234567-1.')], verbose_name='CNIC / B-Form Number'),
        ),
    ]
