# Generated by Django 5.2.17 on 2026-09-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_remove_programpreference_program_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='degree_certificate',
            field=models.CharField(choices=[('matric', 'Matric / SSC'), ('intermediate', 'Intermediate / A-Level'), ('bachelor', "Bachelor's"), ('master', "Master's")], max_length=20, verbose_name='Degree / Certificate'),
        ),
        migrations.AlterField(
            model_name='admissionscheme',
            name='admission_scheme',
            field=models.CharField(choices=[('open_merit', 'Open Merit'), ('self_finance', 'Self Finance'), ('special_quota', 'Special Quota'), ('overseas_pakistani', 'Overseas Pakistani')], max_length=30, verbose_name='Admission Scheme'),
        ),
        migrations.AlterField(
            model_name='admissiontest',
            name='test_center',
            field=models.CharField(choices=[('peshawar', 'Peshawar'), ('lahore', 'Lahore'), ('karachi', 'Karachi'), ('islamabad', 'Islamabad'), ('quetta', 'Quetta'), ('multan', 'Multan')], max_length=20),
        ),
        migrations.AlterField(
            model_name='admissiontest',
            name='test_type',
            field=models.CharField(blank=True, choices=[('nts', 'NTS'), ('ecat', 'ECAT'), ('mcat', 'MCAT'), ('sat', 'SAT'), ('university_specific', 'University-Specific Test')], max_length=30),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='nationality',
            field=models.CharField(choices=[('Afghan', 'Afghan'), ('Albanian', 'Albanian'), ('Algerian', 'Algerian'), ('American', 'American'), ('Andorran', 'Andorran'), ('Angolan', 'Angolan'), ('Antiguan and Barbudan', 'Antiguan and Barbudan'), ('Argentine', 'Argentine'), ('Armenian', 'Armenian'), ('Australian', 'Australian'), ('Austrian', 'Austrian'), ('Azerbaijani', 'Azerbaijani'), ('Bahamian', 'Bahamian'), ('Bahraini', 'Bahraini'), ('Bangladeshi', 'Bangladeshi'), ('Barbadian', 'Barbadian'), ('Belarusian', 'Belarusian'), ('Belgian', 'Belgian'), ('Belizean', 'Belizean'), ('Beninese', 'Beninese'), ('Bhutanese', 'Bhutanese'), ('Bolivian', 'Bolivian'), ('Bosnian', 'Bosnian'), ('Botswanan', 'Botswanan'), ('Brazilian', 'Brazilian'), ('Bruneian', 'Bruneian'), ('Bulgarian', 'Bulgarian'), ('Burkinabe', 'Burkinabe'), ('Burundian', 'Burundian'), ('Cabo Verdean', 'Cabo Verdean'), ('Cambodian', 'Cambodian'), ('Cameroonian', 'Cameroonian'), ('Canadian', 'Canadian'), ('Central African', 'Central African'), ('Chadian', 'Chadian'), ('Chilean', 'Chilean'), ('Chinese', 'Chinese'), ('Colombian', 'Colombian'), ('Comorian', 'Comorian'), ('Congolese', 'Congolese'), ('Costa Rican', 'Costa Rican'), ('Croatian', 'Croatian'), ('Cuban', 'Cuban'), ('Cypriot', 'Cypriot'), ('Czech', 'Czech'), ('Danish', 'Danish'), ('Djiboutian', 'Djiboutian'), ('Dominican', 'Dominican'), ('Dutch', 'Dutch'), ('Ecuadorian', 'Ecuadorian'), ('Egyptian', 'Egyptian'), ('Emirati', 'Emirati'), ('Equatorial Guinean', 'Equatorial Guinean'), ('Eritrean', 'Eritrean'), ('Estonian', 'Estonian'), ('Eswatini', 'Eswatini'), ('Ethiopian', 'Ethiopian'), ('Fijian', 'Fijian'), ('Finnish', 'Finnish'), ('French', 'French'), ('Gabonese', 'Gabonese'), ('Gambian', 'Gambian'), ('Georgian', 'Georgian'), ('German', 'German'), ('Ghanaian', 'Ghanaian'), ('Greek', 'Greek'), ('Grenadian', 'Grenadian'), ('Guatemalan', 'Guatemalan'), ('Guinean', 'Guinean'), ('Guyanese', 'Guyanese'), ('Haitian', 'Haitian'), ('Honduran', 'Honduran'), ('Hungarian', 'Hungarian'), ('Icelandic', 'Icelandic'), ('Indian', 'Indian'), ('Indonesian', 'Indonesian'), ('Iranian', 'Iranian'), ('Iraqi', 'Iraqi'), ('Irish', 'Irish'), ('Italian', 'Italian'), ('Ivorian', 'Ivorian'), ('Jamaican', 'Jamaican'), ('Japanese', 'Japanese'), ('Jordanian', 'Jordanian'), ('Kazakhstani', 'Kazakhstani'), ('Kenyan', 'Kenyan'), ('Kiribati', 'Kiribati'), ('Kuwaiti', 'Kuwaiti'), ('Kyrgyzstani', 'Kyrgyzstani'), ('Laotian', 'Laotian'), ('Latvian', 'Latvian'), ('Lebanese', 'Lebanese'), ('Lesotho', 'Lesotho'), ('Liberian', 'Liberian'), ('Libyan', 'Libyan'), ('Liechtensteiner', 'Liechtensteiner'), ('Lithuanian', 'Lithuanian'), ('Luxembourgish', 'Luxembourgish'), ('Malagasy', 'Malagasy'), ('Malawian', 'Malawian'), ('Malaysian', 'Malaysian'), ('Maldivian', 'Maldivian'), ('Malian', 'Malian'), ('Maltese', 'Maltese'), ('Marshallese', 'Marshallese'), ('Mauritanian', 'Mauritanian'), ('Mauritian', 'Mauritian'), ('Mexican', 'Mexican'), ('Micronesian', 'Micronesian'), ('Moldovan', 'Moldovan'), ('Monegasque', 'Monegasque'), ('Mongolian', 'Mongolian'), ('Montenegrin', 'Montenegrin'), ('Moroccan', 'Moroccan'), ('Mozambican', 'Mozambican'), ('Myanmar', 'Myanmar'), ('Namibian', 'Namibian'), ('Nauruan', 'Nauruan'), ('Nepalese', 'Nepalese'), ('Dutch', 'Dutch'), ('New Zealander', 'New Zealander'), ('Nicaraguan', 'Nicaraguan'), ('Nigerian', 'Nigerian'), ('Nigerien', 'Nigerien'), ('North Korean', 'North Korean'), ('North Macedonian', 'North Macedonian'), ('Norwegian', 'Norwegian'), ('Omani', 'Omani'), ('Pakistani', 'Pakistani'), ('Palauan', 'Palauan'), ('Panamanian', 'Panamanian'), ('Papua New Guinean', 'Papua New Guinean'), ('Paraguayan', 'Paraguayan'), ('Peruvian', 'Peruvian'), ('Philippine', 'Philippine'), ('Polish', 'Polish'), ('Portuguese', 'Portuguese'), ('Qatari', 'Qatari'), ('Romanian', 'Romanian'), ('Russian', 'Russian'), ('Rwandan', 'Rwandan'), ('Saint Lucian', 'Saint Lucian'), ('Salvadoran', 'Salvadoran'), ('Samoan', 'Samoan'), ('San Marinese', 'San Marinese'), ('Saudi', 'Saudi'), ('Senegalese', 'Senegalese'), ('Serbian', 'Serbian'), ('Seychellois', 'Seychellois'), ('Sierra Leonean', 'Sierra Leonean'), ('Singaporean', 'Singaporean'), ('Slovak', 'Slovak'), ('Slovenian', 'Slovenian'), ('Solomon Islander', 'Solomon Islander'), ('Somali', 'Somali'), ('South African', 'South African'), ('South Korean', 'South Korean'), ('South Sudanese', 'South Sudanese'), ('Spanish', 'Spanish'), ('Sri Lankan', 'Sri Lankan'), ('Sudanese', 'Sudanese'), ('Surinamese', 'Surinamese'), ('Swedish', 'Swedish'), ('Swiss', 'Swiss'), ('Syrian', 'Syrian'), ('Taiwanese', 'Taiwanese'), ('Tajikistani', 'Tajikistani'), ('Tanzanian', 'Tanzanian'), ('Thai', 'Thai'), ('Timorese', 'Timorese'), ('Togolese', 'Togolese'), ('Tongan', 'Tongan'), ('Trinidadian and Tobagonian', 'Trinidadian and Tobagonian'), ('Tunisian', 'Tunisian'), ('Turkish', 'Turkish'), ('Turkmen', 'Turkmen'), ('Tuvaluan', 'Tuvaluan'), ('Ugandan', 'Ugandan'), ('Ukrainian', 'Ukrainian'), ('Uruguayan', 'Uruguayan'), ('Uzbekistani', 'Uzbekistani'), ('Vanuatuan', 'Vanuatuan'), ('Venezuelan', 'Venezuelan'), ('Vietnamese', 'Vietnamese'), ('Yemeni', 'Yemeni'), ('Zambian', 'Zambian'), ('Zimbabwean', 'Zimbabwean')], default='Pakistani', max_length=50),
        ),
        migrations.AlterField(
            model_name='programpreference',
            name='discipline',
            field=models.CharField(choices=[('computer_engineering', 'Computer Engineering'), ('computer_science', 'Computer Science'), ('chemical_engineering', 'Chemical Engineering'), ('civil_engineering', 'Civil Engineering'), ('electronics_engineering', 'Electronics Engineering'), ('electrical_engineering', 'Electrical Engineering'), ('engineering_sciences_applied_mathematics', 'Engineering Sciences (Applied Mathematics)'), ('engineering_sciences_applied_physics', 'Engineering Sciences (Applied Physics)'), ('engineering_sciences_engineering', 'Engineering Sciences (Engineering)'), ('mechanical_engineering', 'Mechanical Engineering'), ('materials_engineering', 'Materials Engineering'), ('nanotechnology_materials_engineering', 'Nanotechnology and Materials Engineering'), ('engineering_management', 'Engineering Management')], max_length=50),
        ),
        migrations.AlterField(
            model_name='testcenter',
            name='preferred_test_center',
            field=models.CharField(choices=[('peshawar', 'Peshawar'), ('lahore', 'Lahore'), ('karachi', 'Karachi'), ('islamabad', 'Islamabad'), ('quetta', 'Quetta'), ('multan', 'Multan')], max_length=20, verbose_name='Preferred Test Center'),
        ),
    ]
