# Generated by Django 5.2.17 on 2026-09-01 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_alter_academicinfo_degree_certificate_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormSubmission',
            new_name='ApplicationForm',
        ),
    ]
