# Generated by Django 5.2.17 on 2026-09-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_rename_formsubmission_applicationform'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_attended',
            field=models.BooleanField(default=False, help_text='Marked true once the applicant has attended their interview.'),
        ),
        migrations.AddField(
            model_name='application',
            name='test_completed',
            field=models.BooleanField(default=False, help_text='Marked true once the applicant has taken the entry test.'),
        ),
    ]
