# Generated by Django 5.2.17 on 2026-09-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_application_interview_attended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='decision_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='entry_test_result',
            field=models.CharField(choices=[('not_taken', 'Not Taken'), ('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed')], default='not_taken', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='final_decision',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_status',
            field=models.CharField(choices=[('not_scheduled', 'Not Scheduled'), ('scheduled', 'Scheduled'), ('attended', 'Attended'), ('missed', 'Missed')], default='not_scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='test_result_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='test_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
