# Generated by Django 5.2.17 on 2026-08-16 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_remove_retired_application_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid 11-digit Pakistani phone number.', regex='^03\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='city',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator("^[A-Za-z]+(?:[ '-][A-Za-z]+)*$", 'Use letters, spaces, hyphens, or apostrophes only.')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='district',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator("^[A-Za-z]+(?:[ '-][A-Za-z]+)*$", 'Use letters, spaces, hyphens, or apostrophes only.')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='domicile_district',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator("^[A-Za-z]+(?:[ '-][A-Za-z]+)*$", 'Use letters, spaces, hyphens, or apostrophes only.')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator("^[A-Za-z]+(?:[ '-][A-Za-z]+)*$", 'Use letters, spaces, hyphens, or apostrophes only.')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter a valid 10 digit mobile number.')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='father_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator("^[A-Za-z]+(?:[ '-][A-Za-z]+)*$", 'Use letters, spaces, hyphens, or apostrophes only.')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator("^[A-Za-z]+(?:[-'][A-Za-z]+)*$", 'Use letters only.')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='application',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator("^[A-Za-z]+(?:[ '-][A-Za-z]+)*$", 'Use letters, spaces, hyphens, or apostrophes only.')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter a valid 10 digit mobile number.')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator("^[A-Za-z]+(?:[-'][A-Za-z]+)*$", 'Use letters only.')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='mother_name',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator("^[A-Za-z]+(?:[ '-][A-Za-z]+)*$", 'Use letters, spaces, hyphens, or apostrophes only.')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter a valid 10 digit mobile number.')]),
        ),
    ]
