# Generated by Django 5.2.17 on 2026-08-16

import django.core.validators
from django.db import migrations, models


PHONE_FIELDS = (
    "phone",
    "alternate_phone",
    "guardian_phone",
    "emergency_contact_number",
)


def add_country_code(apps, schema_editor):
    Application = apps.get_model("applications", "Application")
    for application in Application.objects.all().iterator():
        changed_fields = []
        for field_name in PHONE_FIELDS:
            value = getattr(application, field_name)
            if value and len(value) == 10 and value.isdigit():
                setattr(application, field_name, f"92{value}")
                changed_fields.append(field_name)
        if changed_fields:
            application.save(update_fields=changed_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0009_alter_application_alternate_phone_and_more"),
    ]

    operations = [
        migrations.RunPython(add_country_code, migrations.RunPython.noop),
        *[
            migrations.AlterField(
                model_name="application",
                name=field_name,
                field=models.CharField(
                    blank=True,
                    max_length=12,
                    validators=[django.core.validators.RegexValidator(
                        message="Enter a valid phone number starting with 92 followed by 10 digits.",
                        regex="^92\\d{10}$",
                    )],
                ),
            )
            for field_name in PHONE_FIELDS
        ],
    ]
