# Generated by Django 5.2.17 on 2026-08-16 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_standardize_phone_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='email_address',
        ),
        migrations.AlterField(
            model_name='application',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator('^92\\d{10}$', 'Enter a valid phone number starting with 92 followed by 10 digits.')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator('^92\\d{10}$', 'Enter a valid phone number starting with 92 followed by 10 digits.')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator('^92\\d{10}$', 'Enter a valid phone number starting with 92 followed by 10 digits.')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator('^92\\d{10}$', 'Enter a valid phone number starting with 92 followed by 10 digits.')]),
        ),
    ]
