# Generated by Django 5.2.17 on 2026-09-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='program',
            field=models.CharField(blank=True, choices=[('MS', 'MS'), ('PHD', 'PhD')], default='', max_length=10),
        ),
    ]
