# Generated by Django 5.2.17 on 2026-08-16

import django.core.validators
from django.db import migrations, models


def add_country_code(apps, schema_editor):
    Profile = apps.get_model("accounts", "Profile")
    for profile in Profile.objects.all().iterator():
        if profile.phone and len(profile.phone) == 10 and profile.phone.isdigit():
            profile.phone = f"92{profile.phone}"
            profile.save(update_fields=["phone"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_profile_phone"),
    ]

    operations = [
        migrations.RunPython(add_country_code, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=12,
                validators=[django.core.validators.RegexValidator(
                    message="Enter a valid phone number starting with 92 followed by 10 digits.",
                    regex="^92\\d{10}$",
                )],
            ),
        ),
    ]
