# Generated by Django 5.2.17 on 2026-08-16 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_standardize_phone_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator('^92\\d{10}$', 'Enter a valid phone number starting with 92 followed by 10 digits.')]),
        ),
    ]
