# Generated by Django 5.2.17 on 2026-08-30 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('cnic_bform', 'CNIC Copy'), ('father_cnic', "Father's CNIC Copy"), ('matric_certificate', 'Matric Certificate'), ('intermediate_certificate', 'Intermediate Certificate'), ('domicile_certificate', 'Domicile Certificate')], max_length=30)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/')),
                ('status', models.CharField(choices=[('not_uploaded', 'Not Uploaded'), ('uploaded', 'Uploaded'), ('under_verification', 'Under Verification'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('replace_required', 'Replace Required')], default='not_uploaded', max_length=25)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application')),
            ],
            options={
                'unique_together': {('application', 'doc_type')},
            },
        ),
    ]
