# Generated by Django 5.2.17 on 2026-08-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('cnic_bform', 'CNIC / B-Form Copy'), ('father_cnic', "Father's CNIC Copy"), ('matric_certificate', 'Matric Certificate'), ('intermediate_certificate', 'Intermediate Certificate'), ('character_certificate', 'Character Certificate'), ('domicile_certificate', 'Domicile Certificate')], max_length=30),
        ),
    ]
